import React, { useState, useEffect, useRef, useCallback, useMemo, forwardRef, useImperativeHandle } from 'react';
import { useTranslation } from 'react-i18next';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import axios from 'axios';
import { Loader2, AlertTriangle, FileText } from 'lucide-react';
import { recordPageView } from '../../services/api';
import { useLinkClickTracking } from '../../hooks/useLinkClickTracking';
import { isSafeUrl } from '../../lib/utils';
import { getLocalizedErrorMessage } from '../../utils/errorTranslator';

/**
 * Generates an SVG watermark pattern matching PdfJsViewer / PreviewViewer / SpreadsheetViewer.
 */
function buildWatermarkSvg(text) {
  const safe = (text || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="340" height="180" viewBox="0 0 340 180">
    <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle"
      transform="rotate(-28 170 90)" fill="#000000" font-family="sans-serif"
      font-size="14" font-weight="500" letter-spacing="0.5">${safe}</text>
  </svg>`;
}

/**
 * Sanitizes raw HTML output generated by marked.
 * Preserves in-page '#' anchors while sanitizing external links and images.
 */
function sanitizeMarkdownHtml(rawHtml) {
  const hook = (node) => {
    if (node.tagName === 'A' && node.hasAttribute('href')) {
      const href = node.getAttribute('href');
      if (href.startsWith('#')) {
        // In-page internal anchor: retain without target="_blank"
        return;
      }
      if (!isSafeUrl(href)) {
        node.removeAttribute('href');
      } else {
        node.setAttribute('target', '_blank');
        node.setAttribute('rel', 'noopener noreferrer');
      }
    }
    if (node.tagName === 'IMG' && node.hasAttribute('src')) {
      const src = node.getAttribute('src');
      if (!isSafeUrl(src)) {
        node.removeAttribute('src');
      } else {
        node.setAttribute('loading', 'lazy');
        node.setAttribute('referrerpolicy', 'no-referrer');
      }
    }
  };

  DOMPurify.addHook('afterSanitizeAttributes', hook);
  try {
    return DOMPurify.sanitize(rawHtml, {
      ALLOWED_TAGS: [
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'a', 'b', 'strong', 'i', 'em',
        'ul', 'ol', 'li', 'blockquote', 'code', 'pre', 'table', 'thead', 'tbody',
        'tr', 'th', 'td', 'hr', 'br', 'img', 'del', 'sup', 'sub', 'span', 'section'
      ],
      ALLOWED_ATTR: [
        'href', 'src', 'alt', 'title', 'class', 'id', 'target', 'rel',
        'loading', 'referrerpolicy', 'width', 'height'
      ],
      SANITIZE_NAMED_PROPS: true,
    });
  } finally {
    DOMPurify.removeHook('afterSanitizeAttributes');
  }
}

export const MarkdownViewer = forwardRef(({
  markdownUrl,
  title = 'Markdown Document',
  viewId,
  dataroomVisitId,
  watermarkText = '',
  allowDownload = true,
  canCopy = null,
  documentData = null,
  zoomLevel = 1,
}, ref) => {
  const { t } = useTranslation();
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const containerRef = useRef(null);
  const contentRef = useRef(null);
  const maxScrollPercentageRef = useRef(0);
  const lastSentScrollPercentageRef = useRef(0);
  const durationRef = useRef(0);
  const intervalRef = useRef(null);
  const isInactiveRef = useRef(false);
  const inactivityTimerRef = useRef(null);

  const urlToFetch = markdownUrl || documentData?.markdown_preview_url;
  const isProtected = canCopy !== null ? !canCopy : (Boolean(watermarkText) || !allowDownload);
  const handleLinkClick = useLinkClickTracking(viewId, dataroomVisitId);

  // Expose imperative methods
  useImperativeHandle(ref, () => ({
    scrollToTop: () => {
      if (containerRef.current) {
        containerRef.current.scrollTo({ top: 0, behavior: 'smooth' });
      }
    },
    getContainer: () => containerRef.current,
  }));

  // Fetch markdown source
  useEffect(() => {
    if (!urlToFetch) {
      if (documentData && documentData.preview_mode !== 'markdown') {
        setError(t('errors.unsupportedFormat', 'Document is not a markdown file.'));
      } else {
        setError(t('errors.notFound', 'Markdown preview URL not found.'));
      }
      setLoading(false);
      return;
    }

    let isMounted = true;
    setLoading(true);
    setError(null);

    axios.get(urlToFetch, { responseType: 'text' })
      .then((res) => {
        if (isMounted) {
          setContent(typeof res.data === 'string' ? res.data : JSON.stringify(res.data));
          setLoading(false);
        }
      })
      .catch((err) => {
        if (isMounted) {
          setError(getLocalizedErrorMessage(err, 'viewer.previewFailed'));
          setLoading(false);
        }
      });

    return () => {
      isMounted = false;
    };
  }, [urlToFetch, documentData?.preview_mode, t]);

  // Parse & sanitize markdown to HTML
  const sanitizedHtml = useMemo(() => {
    if (!content) return '';
    try {
      const rawHtml = marked.parse(content, { gfm: true, breaks: true });
      return sanitizeMarkdownHtml(rawHtml);
    } catch (err) {
      console.error('Failed to parse markdown:', err);
      return `<p class="text-red-500">${t('errors.parseFailed', 'Failed to parse markdown content.')}</p>`;
    }
  }, [content, t]);

  // Compute scroll percentage
  const updateScrollPercentage = useCallback(() => {
    const el = containerRef.current;
    if (!el) return;
    const { scrollTop, scrollHeight, clientHeight } = el;
    let pct = 100;
    if (scrollHeight > clientHeight) {
      pct = Math.min(100, Math.max(0, Math.floor(((scrollTop + clientHeight) / scrollHeight) * 100)));
    }
    if (pct > maxScrollPercentageRef.current) {
      maxScrollPercentageRef.current = pct;
    }
  }, []);

  // Update initial scroll percentage when content renders
  useEffect(() => {
    if (!loading && sanitizedHtml) {
      // Delay slightly for DOM layout computation
      const timer = setTimeout(updateScrollPercentage, 50);
      return () => clearTimeout(timer);
    }
  }, [loading, sanitizedHtml, updateScrollPercentage]);

  // Scroll event handler
  const handleScroll = useCallback(() => {
    updateScrollPercentage();
  }, [updateScrollPercentage]);

  // Send tracking telemetry
  const sendTrackingData = useCallback((duration, useBeacon = false) => {
    const hasNewScroll = maxScrollPercentageRef.current > lastSentScrollPercentageRef.current;
    if (!viewId || (duration < 1 && !hasNewScroll)) return;
    const payload = {
      view_session: viewId,
      page_number: 1,
      duration_seconds: Math.round(duration),
      scroll_percentage: maxScrollPercentageRef.current,
      media_type: 'markdown',
    };
    if (dataroomVisitId) {
      payload.dataroom_visit = dataroomVisitId;
    }
    lastSentScrollPercentageRef.current = maxScrollPercentageRef.current;
    recordPageView(payload, useBeacon);
  }, [viewId, dataroomVisitId]);

  // Inactivity detection (60 seconds)
  useEffect(() => {
    if (!viewId) return;

    const INACTIVITY_TIMEOUT = 60000;
    const handleActivity = () => {
      isInactiveRef.current = false;
      clearTimeout(inactivityTimerRef.current);
      inactivityTimerRef.current = setTimeout(() => {
        isInactiveRef.current = true;
      }, INACTIVITY_TIMEOUT);
    };

    const events = ['mousemove', 'keydown', 'scroll', 'mousedown'];
    events.forEach((event) => window.addEventListener(event, handleActivity));
    handleActivity();

    return () => {
      events.forEach((event) => window.removeEventListener(event, handleActivity));
      clearTimeout(inactivityTimerRef.current);
    };
  }, [viewId]);

  // Time tracking interval and periodic flushing
  useEffect(() => {
    if (!viewId) return;

    const tick = () => {
      if (!isInactiveRef.current && !document.hidden) {
        durationRef.current += 1;
        // Flush every 30 seconds of active viewing
        if (durationRef.current >= 30) {
          sendTrackingData(durationRef.current);
          durationRef.current = 0;
        }
      }
    };

    intervalRef.current = setInterval(tick, 1000);

    return () => {
      clearInterval(intervalRef.current);
      const hasNewScroll = maxScrollPercentageRef.current > lastSentScrollPercentageRef.current;
      if (durationRef.current >= 1 || hasNewScroll) {
        sendTrackingData(durationRef.current);
        durationRef.current = 0;
      }
    };
  }, [viewId, sendTrackingData]);

  // Send final telemetry on page unload
  useEffect(() => {
    const handleBeforeUnload = () => {
      const hasNewScroll = maxScrollPercentageRef.current > lastSentScrollPercentageRef.current;
      if (durationRef.current >= 1 || hasNewScroll) {
        sendTrackingData(durationRef.current, true);
        durationRef.current = 0;
      }
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
    };
  }, [sendTrackingData]);

  // Delegated link click handling (smooth scroll for anchors, tracking for external)
  const handleContentClick = useCallback((e) => {
    const anchor = e.target.closest('a');
    if (!anchor) return;

    const href = anchor.getAttribute('href');
    if (!href) return;

    if (href.startsWith('#')) {
      // In-page anchor fragment navigation
      e.preventDefault();
      const targetId = href.slice(1);
      if (targetId && containerRef.current) {
        const stripped = targetId.startsWith('user-content-') ? targetId.slice(13) : targetId;
        try {
          const targetEl = containerRef.current.querySelector(`#${CSS.escape(targetId)}`) ||
                           containerRef.current.querySelector(`#user-content-${CSS.escape(stripped)}`) ||
                           containerRef.current.querySelector(`[name="${CSS.escape(targetId)}"]`) ||
                           containerRef.current.querySelector(`[name="user-content-${CSS.escape(stripped)}"]`);
          if (targetEl) {
            targetEl.scrollIntoView({ behavior: 'smooth', block: 'start' });
          }
        } catch (_err) {
          // Fallback if selector parsing fails: container-scoped search without CSS.escape
          const el = Array.from(containerRef.current.querySelectorAll('[id], [name]')).find(
            (candidate) => {
              const id = candidate.getAttribute('id');
              const name = candidate.getAttribute('name');
              return id === targetId || id === `user-content-${stripped}` || name === targetId || name === `user-content-${stripped}`;
            }
          );
          if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      }
      return;
    }

    // Outbound link click telemetry
    handleLinkClick(href, 1);
  }, [handleLinkClick]);

  // Clipboard copy protection
  const handleCopy = useCallback((e) => {
    if (isProtected) {
      e.preventDefault();
    }
  }, [isProtected]);

  return (
    <div
      ref={containerRef}
      onScroll={handleScroll}
      onCopy={handleCopy}
      className={`relative h-full w-full overflow-y-auto bg-white ${
        isProtected ? 'select-none' : ''
      }`}
      tabIndex={0}
      role="region"
      aria-label={title}
    >
      {/* Loading state */}
      {loading && (
        <div className="flex h-full min-h-[400px] w-full flex-col items-center justify-center p-8 text-center">
          <Loader2 className="mb-3 h-8 w-8 animate-spin text-primary" />
          <p className="text-sm text-gray-500">{t('viewer.loadingMarkdown', 'Loading Markdown document...')}</p>
        </div>
      )}

      {/* Error state */}
      {!loading && error && (
        <div className="flex h-full min-h-[400px] w-full flex-col items-center justify-center p-8 text-center">
          <div className="mb-3 rounded-full bg-red-50 p-3 text-red-600">
            <AlertTriangle className="h-6 w-6" />
          </div>
          <p className="mb-1 text-base font-medium text-gray-900">{t('viewer.previewFailed', 'Preview unavailable')}</p>
          <p className="text-sm text-gray-500">{error}</p>
        </div>
      )}

      {/* Content display */}
      {!loading && !error && (
        <div
          ref={contentRef}
          onClick={handleContentClick}
          style={zoomLevel !== 1 ? { zoom: zoomLevel } : undefined}
          className="mx-auto max-w-4xl px-6 py-8 sm:px-12 sm:py-12"
        >
          <article
            className="prose prose-slate max-w-none dark:prose-invert prose-headings:font-semibold prose-a:text-blue-600 hover:prose-a:underline prose-img:rounded-lg prose-table:overflow-x-auto"
            dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
          />
        </div>
      )}

      {/* Watermark Overlay */}
      {watermarkText && (
        <div
          data-testid="markdown-watermark"
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 overflow-hidden select-none z-30"
          style={{
            backgroundImage: `url("data:image/svg+xml,${encodeURIComponent(buildWatermarkSvg(watermarkText))}")`,
            backgroundSize: '340px 180px',
            backgroundRepeat: 'repeat',
            opacity: 0.18,
          }}
        />
      )}
    </div>
  );
});

MarkdownViewer.displayName = 'MarkdownViewer';
