# Generated by Django 5.2.6 on 2025-10-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0001_initial'),
        ('documents', '0024_sharelink_sharelink_exactly_one_target'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sharelinkdataroomsetting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dataroom_document__isnull', False), ('dataroom_folder__isnull', True)), models.Q(('dataroom_document__isnull', True), ('dataroom_folder__isnull', False)), _connector='OR'), name='sharelinkdataroomsetting_exactly_one_target'),
        ),
    ]
