# Generated by Django 5.2.6 on 2026-04-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomdocument',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomfolder',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
