# Generated by Django 5.2.6 on 2025-12-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataroomdocument',
            unique_together={('dataroom', 'document', 'folder')},
        ),
        migrations.AddField(
            model_name='dataroomdocument',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
