# Generated by Django 5.2.6 on 2025-12-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0002_alter_dataroomdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
