# Generated by Django 5.2.6 on 2026-05-02 06:08

import core.fields
import datarooms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0002_dataroomdocument_is_starred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroom',
            name='brand_accent_color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='brand_primary_color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='brand_secondary_color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='branding_banner',
            field=models.ImageField(blank=True, null=True, upload_to=datarooms.models.dataroom_branding_banner_path),
        ),
        migrations.AddField(
            model_name='dataroom',
            name='show_file_index',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DataroomItemOrder',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('folder', 'Folder'), ('document', 'Document')], max_length=16)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='datarooms.dataroom')),
                ('dataroom_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to='datarooms.dataroomdocument')),
                ('folder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to='datarooms.dataroomfolder')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_item_orders', to='datarooms.dataroomfolder')),
            ],
            options={
                'indexes': [models.Index(fields=['dataroom', 'parent_folder', 'position'], name='datarooms_d_dataroo_7e0ad9_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataroom', 'parent_folder', 'position'), name='uq_dataroom_item_order_scope_position'), models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'folder'), ('folder__isnull', False), ('dataroom_document__isnull', True)), models.Q(('item_type', 'document'), ('folder__isnull', True), ('dataroom_document__isnull', False)), _connector='OR'), name='ck_dataroom_item_order_target_matches_type')],
            },
        ),
    ]
