# Generated by Django 5.2.6 on 2026-08-28 14:25

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0004_dataroom_enable_qna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomfolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataroom_folders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DataroomCollaborator',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('collaborator', 'Collaborator')], default='collaborator', max_length=20)),
                ('dataroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='datarooms.dataroom')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators_invited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('dataroom', 'user'), name='uq_dataroom_collaborator_dataroom_user')],
            },
        ),
    ]
