# Generated by Django 5.2.6 on 2026-04-09 13:37

import core.fields
import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_loginactivity'),
        ('datarooms', '0001_initial'),
        ('sharelinks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationDestination',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('destination_type', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('wechat', 'WeChat Work'), ('feishu', 'FeiShu'), ('webhook', 'Webhook')], default='webhook', max_length=20)),
                ('endpoint_url', models.URLField(max_length=2048)),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT')], default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signing_secret', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_destinations_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_destinations', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('share_link', 'Share Link'), ('dataroom', 'Dataroom')], default='global', max_length=20)),
                ('subscribed_events', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules_created', to=settings.AUTH_USER_MODEL)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='datarooms.dataroom')),
                ('destinations', models.ManyToManyField(blank=True, related_name='rules', to='automations.automationdestination')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='core.organization')),
                ('share_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='sharelinks.sharelink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationDelivery',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body_excerpt', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_deliveries', to='core.organization')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='automations.automationdestination')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='automations.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAssignment',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_assignments', to='core.organization')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='automations.automationdelivery')),
                ('assigned_by_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='automations.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automationdestination',
            index=models.Index(fields=['organization', 'name'], name='automations_organiz_8f10fd_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization', 'name'], name='automations_organiz_564148_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dataroom__isnull', True), ('scope_type', 'global'), ('share_link__isnull', True)), models.Q(('dataroom__isnull', True), ('scope_type', 'share_link'), ('share_link__isnull', False)), models.Q(('dataroom__isnull', False), ('scope_type', 'dataroom'), ('share_link__isnull', True)), _connector='OR'), name='automationrule_scope_target_consistency'),
        ),
    ]
