# Generated by Django 5.2.6 on 2026-07-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationdestination',
            name='destination_type',
            field=models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('wechat', 'WeChat Work'), ('feishu', 'FeiShu'), ('webhook', 'Webhook'), ('email', 'Email')], default='webhook', max_length=20),
        ),
        migrations.AlterField(
            model_name='automationdestination',
            name='endpoint_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
