# Generated by Django 5.2.6 on 2026-04-08 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        ('core', '0002_loginactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationdestination',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='automationdestination',
            index=models.Index(fields=['organization', 'name'], name='automations_organiz_8f10fd_idx'),
        ),
    ]
