# Generated by Django 5.2.6 on 2026-07-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_alter_automationdestination_destination_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('dead_letter', 'Dead Letter')], default='pending', max_length=20),
        ),
    ]
