# Generated by Django 5.2.6 on 2026-04-08 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_alter_automationdestination_unique_together_and_more'),
        ('core', '0002_loginactivity'),
        ('datarooms', '0001_initial'),
        ('sharelinks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationrule',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization', 'name'], name='automations_organiz_564148_idx'),
        ),
    ]
