services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    ports:
      - "8080:8080"    
    environment:
      - PORT=8080
      - STORAGE_PATH=/storage
      - INTERNAL_API_TOKEN=supersecrettoken # Replace with a real secret in prod
    volumes:
      - ./core:/app
      - ~/.coneshare-data:/storage

  backend:
    image: coneshare:dev
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    command: python manage.py runserver 0.0.0.0:8000
    # command: tail -f /dev/null
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - redis
      - core
    environment:
      - CORE_API_URL=http://core:8080
      - INTERNAL_API_TOKEN=supersecrettoken

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  celery_worker:
    image: coneshare:dev
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile-dev
    command: celery -A backend worker -l INFO
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - backend
      - redis
      - core
    environment:
      - CORE_API_URL=http://core:8080
      - INTERNAL_API_TOKEN=supersecrettoken

  frontend:
    image: coneshare:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  redis_data:
