services:
  core:
    build: ./core
    restart: unless-stopped
    volumes:
      - media_volume:/storage
    environment:
      - PORT=8080
      - STORAGE_PATH=/storage
      # TODO: Set a strong, unique INTERNAL_API_TOKEN in a .env file for production
      - INTERNAL_API_TOKEN=supersecrettoken

  backend:
    image: coneshare:dev
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    restart: unless-stopped
    depends_on:
      - redis
      - core
    environment:
      - CORE_API_URL=http://core:8080
      # TODO: Set a strong, unique INTERNAL_API_TOKEN in a .env file for production
      - INTERNAL_API_TOKEN=supersecrettoken
      - STORAGE_TYPE=FILESYSTEM
      - DEBUG=0
      # TODO: Set a strong, unique SECRET_KEY in a .env file for production
      - SECRET_KEY=django-insecure-(ptz@00bnu41y5xkt51b6qi23hqv9@8our!x+14vi7r)9ga)#b
      # TODO: Set the correct domain for your site in a .env file
      - SITE_DOMAIN=http://localhost

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  celery_worker:
    image: coneshare:dev
    command: celery -A backend worker -l INFO
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    restart: unless-stopped
    depends_on:
      - backend
      - redis
      - core

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - media_volume:/usr/src/app/media
    depends_on:
      - backend
      - core

volumes:
  media_volume:
  redis_data:
