services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    command: celery -A backend worker -l INFO
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend
