[program:core-serv]
command=/home/coneshare/app/core-serv
directory=/home/coneshare/app
user=coneshare
autostart=true
autorestart=true
stdout_logfile=/home/coneshare/logs/core-serv.out.log
stderr_logfile=/home/coneshare/logs/core-serv.err.log
redirect_stderr=false

