[program:web]
command=/usr/local/bin/gunicorn -c /home/coneshare/runtime/gunicorn.conf.py
directory=/home/coneshare/app
user=coneshare
stdout_logfile=/home/coneshare/logs/supervisor/out.log
stderr_logfile=/home/coneshare/logs/supervisor/error.log
redirect_stderr=true
environment=DJANGO_SETTINGS_MODULE="backend.settings"
