"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import re
import sys
from urllib.parse import urlparse

import dj_database_url
import sentry_sdk
from django.contrib.gis.geoip2 import GeoIP2
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# BOOTSTRAP SETTINGS (read from environment variables)
# ==============================================================================
# These settings are required for the application to start.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

# Site domain is the primary source for host configuration.
SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'http://localhost:5173')

# Derive ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS from SITE_DOMAIN to simplify setup.
# These can still be overridden by setting them directly in the environment.
SITE_HOSTNAME = urlparse(SITE_DOMAIN).hostname

# Default hosts for development and internal Docker networking.
default_hosts = ['127.0.0.1', 'localhost', 'backend']
if SITE_HOSTNAME and SITE_HOSTNAME not in default_hosts:
    default_hosts.append(SITE_HOSTNAME)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', ','.join(default_hosts)).split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', SITE_DOMAIN).split(',')

# File Server (Core Service) Configuration
CORE_API_URL = os.environ.get('CORE_API_URL', 'http://core:8080')
INTERNAL_API_TOKEN = os.environ.get('INTERNAL_API_TOKEN')

# Malware Scan (ClamAV)
MALWARE_SCAN_ENABLED = os.environ.get('MALWARE_SCAN_ENABLED', 'false').lower() in ('true', '1', 't')
CLAMAV_HOST = os.environ.get('CLAMAV_HOST', 'clamav')
CLAMAV_PORT = int(os.environ.get('CLAMAV_PORT', 3310))
MALWARE_SCAN_TIMEOUT_MS = int(os.environ.get('MALWARE_SCAN_TIMEOUT_MS', 10000))
MALWARE_SCAN_FAIL_MODE = os.environ.get('MALWARE_SCAN_FAIL_MODE', 'closed')

# Email Configuration (for sending password resets, etc.)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@coneshare.com')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Comma-separated list of admin recipients for Django error emails.
# Format: "Alice:alice@example.com,Bob:bob@example.com" or "ops@example.com,dev@example.com"
ADMINS_ENV = os.environ.get('ADMINS', '').strip()
ADMINS = []
if ADMINS_ENV:
    for raw_item in ADMINS_ENV.split(','):
        item = raw_item.strip()
        if not item:
            continue
        if ':' in item:
            name, email = item.split(':', 1)
            ADMINS.append((name.strip(), email.strip()))
        else:
            ADMINS.append(('', item))

# Database Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}

# Log Level Configuration
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()

# Error Monitoring (Sentry)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '').strip()
SENTRY_ENVIRONMENT = os.environ.get('SENTRY_ENVIRONMENT', 'development' if DEBUG else 'production')
SENTRY_RELEASE = os.environ.get('SENTRY_RELEASE', 'rolling')
SENTRY_SEND_DEFAULT_PII = os.environ.get('SENTRY_SEND_DEFAULT_PII', 'false').lower() in ('true', '1', 't')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        environment=SENTRY_ENVIRONMENT,
        release=SENTRY_RELEASE,
        send_default_pii=SENTRY_SEND_DEFAULT_PII,
    )


# Redis base URL from environment (should not include database number)
REDIS_BASE_URL = os.environ.get('REDIS_URL', 'redis://redis:6379').rstrip('/')

# Cache Configuration (using Redis)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_BASE_URL}/1",  # Use DB 1 for cache
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Celery Configuration
CELERY_BROKER_URL = f"{REDIS_BASE_URL}/0"  # Use DB 0 for Celery
CELERY_RESULT_BACKEND = f"{REDIS_BASE_URL}/0"  # Use DB 0 for Celery
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_DEFAULT_QUEUE = 'celery'  # for fast, lightweight tasks like email notifications, PDF rendering, file operations)
CELERY_TASK_ROUTES = {
    'documents.tasks.generate_video_stream_task': {'queue': 'video_processing'},  # for resource-intensive, slow video transcoding
}

# Test-specific Celery settings to run tasks synchronously
if 'test' in sys.argv or 'pytest' in sys.modules:
    CELERY_TASK_ALWAYS_EAGER = True


# Document Preview Engine Settings
PDF_PREVIEW_ENGINE = os.environ.get('PDF_PREVIEW_ENGINE', 'server_pages')
if PDF_PREVIEW_ENGINE not in ('pdfjs', 'server_pages'):
    raise ValueError(f"Invalid PDF_PREVIEW_ENGINE: '{PDF_PREVIEW_ENGINE}'. Allowed options are 'pdfjs', 'server_pages'.")

ENABLE_OFFICE_PREVIEW = os.environ.get('ENABLE_OFFICE_PREVIEW', 'true').lower() in ('true', '1', 't')

if ENABLE_OFFICE_PREVIEW and PDF_PREVIEW_ENGINE != 'server_pages':
    raise ValueError("Invalid configuration: ENABLE_OFFICE_PREVIEW cannot be true when PDF_PREVIEW_ENGINE is not 'server_pages'.")

ENABLE_VIDEO_PREVIEW = os.environ.get('ENABLE_VIDEO_PREVIEW', 'false').lower() in ('true', '1', 't')


# ==============================================================================
# APPLICATION STRUCTURE (defined in code)
# ==============================================================================

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'core.apps.CoreConfig',
    'documents',
    'datarooms',
    'sharelinks',
    'analytics',
    'cloudfiles',
    'filerequests',
    'automations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day',
        'user': '200/min',
        'password_verify': '5/min',
        'signup': '5/min',
        'health_check': '1000/min',
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'ConeShare API',
    'DESCRIPTION': 'OpenAPI schema for the ConeShare backend API.',
    'VERSION': '1.6.0',
}

SIMPLE_JWT = {
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

POSSIBLE_PASSWORD_VALIDATORS = {
    'similarity': {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    'min_length': {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': int(os.environ.get('PASSWORD_MIN_LENGTH', 8)),
        }
    },
    'common': {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    'numeric': {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
}

# Get the comma-separated list of enabled validators from the environment.
# Default to enabling all for security.
ENABLED_VALIDATORS_STR = os.environ.get('ENABLED_PASSWORD_VALIDATORS', 'similarity,min_length,common,numeric')
ENABLED_VALIDATOR_KEYS = [key.strip() for key in ENABLED_VALIDATORS_STR.split(',') if key.strip()]

# Build the final list for Django based on the enabled keys.
AUTH_PASSWORD_VALIDATORS = [
    POSSIBLE_PASSWORD_VALIDATORS[key] for key in ENABLED_VALIDATOR_KEYS if key in POSSIBLE_PASSWORD_VALIDATORS
]

if not AUTH_PASSWORD_VALIDATORS:
    # As a safe default, ensure at least a minimum length validator is active if the env var is empty/invalid.
    AUTH_PASSWORD_VALIDATORS = [POSSIBLE_PASSWORD_VALIDATORS['min_length']]

print("AUTH_PASSWORD_VALIDATORS", AUTH_PASSWORD_VALIDATORS)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# Timezone used only for user-facing timestamp display in notifications.
# Internal Django/Celery timestamps remain UTC.
DISPLAY_TIME_ZONE = os.environ.get('DISPLAY_TIME_ZONE') or TIME_ZONE

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User-uploaded content)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Storage Configuration (for FileSystem or MinIO)
STORAGE_TYPE = os.environ.get('STORAGE_TYPE', 'FILESYSTEM')

if STORAGE_TYPE == 'MINIO':
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = os.environ.get('MINIO_ROOT_USER')
    AWS_SECRET_ACCESS_KEY = os.environ.get('MINIO_ROOT_PASSWORD')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('MINIO_BUCKET_NAME', 'coneshare')
    AWS_S3_ENDPOINT_URL = os.environ.get('MINIO_ENDPOINT')  # e.g., 'http://minio:9000'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = 'media'  # Subdirectory within the bucket
else:  # Default to FileSystemStorage
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'


# GeoIP Configuration
GEOIP_PATH = '/geoip'
try:
    GEOIP = GeoIP2()
    print("Successfully initialized GeoIP2.")
except Exception as e:
    GEOIP = None
    print(f"Failed to initialize GeoIP2: {e}")

# Determine the log directory path for coneshare.log
compose_root_log_dir = BASE_DIR.parent / 'logs'
if compose_root_log_dir.is_dir():
    coneshare_log_path = compose_root_log_dir / 'coneshare.log'
else:
    coneshare_log_path = BASE_DIR / 'logs' / 'coneshare.log'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(pathname)s:%(lineno)d: %(levelname)-5s: %(funcName)s()- %(message)s'
        },
        'simple': {
            'format': '%(asctime)s [%(levelname)s] %(name)s:%(lineno)s %(funcName)s %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue'
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'coneshare_log_hdlr': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': coneshare_log_path,
            'maxBytes': 1024 * 1024 * 500,  # 500 MB
            'backupCount': 10,
            'formatter': 'standard',
        },
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'scripts_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(str(BASE_DIR) + '/logs/', 'script.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'standard',
        },
    },
    'loggers': {
        # root logger — catches everything
        '': {
            'handlers': ['console', 'coneshare_log_hdlr'],
            'level': LOG_LEVEL,
        },
        # Django internal logs (optional)
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True
        },
        'django.request': {
            'handlers': [
                'mail_admins', 'coneshare_log_hdlr',
            ],
            'level': LOG_LEVEL,
            'propagate': True
        },
        'tasks': {
            'handlers': [
                'console', 'coneshare_log_hdlr',
            ],
            'level': LOG_LEVEL,
            'propagate': True
        },
        'scripts': {
            'handlers': ['scripts_handler'],
            'level': 'ERROR',
            'propagate': False
        },
    }
}

# ==============================================================================
# DEFAULT APPLICATION SETTINGS
# ==============================================================================
# These settings provide default values for the application. They can be
# overridden by an administrator via the AppConfiguration model in the admin panel.
# The application code should use `core.services.get_dynamic_setting` to read them.

# Maximum file size in megabytes for which a preview will be generated.
# Files larger than this will be marked as download-only.
MAX_PREVIEW_FILE_SIZE_MB = 100

# Maximum file size in megabytes for which a video preview will be generated.
# Files larger than this will be marked as download-only.
MAX_VIDEO_PREVIEW_SIZE_MB = 100


# Maximum number of pages allowed for an in-browser preview.
# Documents with more pages will be available for download only.
MAX_PREVIEW_PAGES = 100

# User-level file size quota in megabytes.
# A value of 0 means unlimited.
FILE_SIZE_QUOTA_MB = 0

# Maximum number of files that can be uploaded in a single upload operation.
MAX_FILES_PER_UPLOAD = 100

# Cloud Services Configuration
# A list of enabled cloud providers.
ENABLED_CLOUD_PROVIDERS = ["dropbox", "google_drive", "nextcloud"]

# A dictionary mapping cloud providers to their default import folder names.
CLOUD_IMPORT_FOLDER_MAPPING = {
    "dropbox": "Dropbox Imports",
    "google_drive": "Google Drive Imports",
    "nextcloud": "Nextcloud Imports",
}

# Maximum file size in megabytes for cloud imports.
CLOUD_IMPORT_MAX_SIZE_MB = 100

# Dropbox API Credentials
# Get these from your Dropbox App Console.
DROPBOX_APP_KEY = ''
DROPBOX_APP_SECRET = ''


# Google Drive API Credentials
# Get these from your Google Cloud Console.
GOOGLE_DRIVE_CLIENT_ID = ''
GOOGLE_DRIVE_CLIENT_SECRET = ''


# Nextcloud API Credentials
# Get these from your Nextcloud Admin Panel.
NEXT_CLOUD_HOST = ''  # e.g., 'https://cloud.example.com'
NEXT_CLOUD_CLIENT_ID = ''
NEXT_CLOUD_CLIENT_SECRET = ''

# Public signup toggle.
ENABLE_PUBLIC_SIGNUP = False

# Whether to flatten watermarked PDFs on download.
FLATTEN_WATERMARKED_DOWNLOADS = False


# Path to the TTF/OTF font file to be used for watermarking.
# This font should support the characters you intend to display (e.g., CJK for Chinese).
# You must provide this font file at the specified path.
WATERMARK_FONT_PATH = '/usr/share/fonts/opentype/noto/NotoSerifCJK-Regular.ttc'

def load_local_settings(module):
    """Import any symbols that begin with A-Z. Append to lists any symbols that begin with "EXTRA_".
    """
    for attr in dir(module):
        match = re.search(r'^EXTRA_(\w+)', attr)
        if match:
            name = match.group(1)
            value = getattr(module, attr)
            try:
                globals()[name] += value
            except KeyError:
                globals()[name] = value
        elif re.search('^[A-Z]', attr):
            globals()[attr] = getattr(module, attr)

try:
    from . import local_settings
    print("loading local_settings ... Done.")
except ImportError:
    pass
else:
    load_local_settings(local_settings)
    del local_settings
