# Generated by Django 5.2.6 on 2025-09-16 07:30

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='original_storage_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='storage_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.IntegerField()),
                ('storage_key', models.CharField(blank=True, max_length=1024)),
                ('original_storage_key', models.CharField(max_length=1024)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('storage_type', models.CharField(blank=True, max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_vertical', models.BooleanField(default=True)),
                ('has_pages', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.IntegerField()),
                ('storage_key', models.CharField(max_length=1024)),
                ('storage_type', models.CharField(blank=True, max_length=20)),
                ('page_links', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.documentversion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
