# Generated by Django 5.2.6 on 2026-02-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
