# Generated by Django 5.2.6 on 2026-02-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_upload_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload_info',
        ),
    ]
