# Generated by Django 5.2.6 on 2026-06-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='render_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='render_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('not_generated', 'Not generated'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='not_applicable', max_length=20),
        ),
    ]
