# Generated by Django 5.2.6 on 2026-07-02

from django.db import migrations

def reset_legacy_previews(apps, schema_editor):
    DocumentVersion = apps.get_model('documents', 'DocumentVersion')
    DocumentPage = apps.get_model('documents', 'DocumentPage')
    
    # Select PDF and Office document versions that are ready, so that they re-render
    # and extract link annotations.
    ready_versions = DocumentVersion.objects.filter(
        render_status='ready',
        document__type__in=['pdf', 'document']
    )
    ready_version_ids = list(ready_versions.values_list('id', flat=True))
    
    # Delete their associated DocumentPage records
    DocumentPage.objects.filter(document_version_id__in=ready_version_ids).delete()
    
    # Update their render_status and has_pages to force re-render
    ready_versions.update(
        render_status='not_generated',
        has_pages=False
    )

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentversion_render_error_and_more'),
    ]

    operations = [
        migrations.RunPython(reset_legacy_previews),
    ]
