# Generated by Django 5.2.6 on 2025-09-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
        ('documents', '0003_folder_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('organization', 'parent', 'name')},
        ),
    ]
