# Generated by Django 5.0.7 on 2024-09-24 12:00

from django.db import migrations

def link_root_documents_to_root_folder(apps, schema_editor):
    """
    Find all documents with folder=NULL and link them to their organization's
    __root__ folder.
    """
    Document = apps.get_model('documents', 'Document')
    Folder = apps.get_model('documents', 'Folder')
    Organization = apps.get_model('core', 'Organization')

    for org in Organization.objects.all():
        try:
            root_folder = Folder.objects.get(organization=org, name='__root__', parent__isnull=True)
            Document.objects.filter(organization=org, folder__isnull=True).update(folder=root_folder)
        except Folder.DoesNotExist:
            # If an org somehow doesn't have a root folder, we can skip it.
            # The post_migrate signal should prevent this in practice.
            pass


def unlink_root_documents(apps, schema_editor):
    """
    Reverse the operation, setting folder to NULL for documents in the __root__ folder.
    This makes the migration reversible.
    """
    Document = apps.get_model('documents', 'Document')
    Folder = apps.get_model('documents', 'Folder')
    Organization = apps.get_model('core', 'Organization')

    for org in Organization.objects.all():
        try:
            root_folder = Folder.objects.get(organization=org, name='__root__', parent__isnull=True)
            Document.objects.filter(organization=org, folder=root_folder).update(folder=None)
        except Folder.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_folder_unique_together'),
        ('core', '0001_initial'), # Add dependency to core models
    ]

    operations = [
        migrations.RunPython(link_root_documents_to_root_folder, reverse_code=unlink_root_documents),
    ]
