# Generated by Django 5.2.6 on 2026-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_reset_legacy_previews'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
