# Generated by Django 5.2.6 on 2026-07-07 04:36

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentversion_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, validators=[documents.models.validate_document_version_metadata]),
        ),
    ]
