# Generated by Django 5.2.6 on 2025-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_previewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='requires_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharelinkpreset',
            name='requires_email',
            field=models.BooleanField(default=False),
        ),
    ]
