# Generated by Django 5.2.6 on 2025-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_sharelink_requires_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='receive_email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharelinkpreset',
            name='receive_email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
