# Generated by Django 5.2.6 on 2025-10-02 08:50

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_sharelink_receive_email_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='view',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('page_number', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='documents.view')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
