# Generated by Django 5.2.6 on 2026-09-06 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_language'),
        ('documents', '0008_folder_folder_type_and_invariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('folder_type', 'vault')), fields=('organization', 'parent', 'name'), name='unique_active_vault_folder_name'),
        ),
    ]
