# Generated by Django 5.2.6 on 2025-10-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_view_completion_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='view',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
