# Generated by Django 5.2.6 on 2025-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_view_ip_address_view_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='view',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='view',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='view',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
