# Generated by Django 5.2.6 on 2025-10-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='viewer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
