# Generated by Django 5.2.6 on 2025-10-06 03:26

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_view_viewer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='view',
        ),
        migrations.CreateModel(
            name='ViewSession',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('viewer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_sessions', to='documents.sharelink')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_sessions', to='documents.viewer')),
            ],
        ),
        migrations.AddField(
            model_name='pageview',
            name='view_session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='documents.viewsession'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
