# Generated by Django 5.2.6 on 2025-10-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_remove_pageview_view_viewsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='sharelink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
