# Generated by Django 5.2.6 on 2025-10-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_sharelink_is_archived_sharelink_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewsession',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
