# Generated by Django 5.2.6 on 2025-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_viewsession_downloaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
