# Generated by Django 5.2.6 on 2025-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_avatar'),
        ('documents', '0014_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('organization', 'folder', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='sharelink',
            unique_together={('document', 'name')},
        ),
    ]
