# Generated by Django 5.2.6 on 2025-10-11 02:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_document_name_alter_document_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('created_by', 'folder', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('created_by', 'parent', 'name')},
        ),
    ]
