# Generated by Django 5.2.6 on 2025-10-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_document_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
