# Generated by Django 5.2.6 on 2025-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sharelinkpreset',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
