# Generated by Django 5.2.6 on 2025-10-21 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_sharelink_watermark_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewsession',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterField(
            model_name='viewsession',
            name='viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
