# Generated by Django 5.2.6 on 2025-10-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_sharelinkpreset_watermark_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='watermark_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
