# Generated by Django 5.2.6 on 2025-10-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_alter_viewsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
