# Generated by Django 5.2.6 on 2025-10-24 10:00

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_document_status_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='sharelink',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
    ]
