# Generated by Django 5.2.6 on 2025-10-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0001_initial'),
        ('documents', '0022_remove_sharelink_password_hash_sharelink_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharelink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='dataroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='datarooms.dataroom'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='documents.document'),
        ),
    ]
