# Generated by Django 5.2.6 on 2025-10-29 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0001_initial'),
        ('documents', '0023_alter_sharelink_unique_together_sharelink_dataroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dataroom__isnull', True), ('document__isnull', False)), models.Q(('dataroom__isnull', False), ('document__isnull', True)), _connector='OR'), name='sharelink_exactly_one_target'),
        ),
    ]
