# Generated by Django 5.2.6 on 2025-11-09 05:12

import core.fields
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_user_avatar'),
        ('datarooms', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('password', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('requires_email', models.BooleanField(default=False)),
                ('requires_email_verification', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=True)),
                ('enable_watermark', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, max_length=255)),
                ('receive_email_notification', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_links_created', to=settings.AUTH_USER_MODEL)),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='datarooms.dataroom')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='PreviewSession',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_sessions', to='sharelinks.sharelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to='sharelinks.sharelink')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLinkDataroomSetting',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('enable_watermark', models.BooleanField(default=False)),
                ('dataroom_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datarooms.dataroomdocument')),
                ('dataroom_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datarooms.dataroomfolder')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_settings', to='sharelinks.sharelink')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLinkPreset',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('expires_in_days', models.IntegerField(blank=True, null=True)),
                ('requires_password', models.BooleanField(default=False)),
                ('requires_email', models.BooleanField(default=False)),
                ('requires_email_verification', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=True)),
                ('enable_watermark', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, max_length=255)),
                ('receive_email_notification', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_link_presets', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ViewSession',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('viewer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_sessions', to='sharelinks.sharelink')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_sessions', to='sharelinks.viewer')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('page_number', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='sharelinks.viewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dataroom__isnull', True), ('document__isnull', False)), models.Q(('dataroom__isnull', False), ('document__isnull', True)), _connector='OR'), name='sharelink_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='sharelinkdataroomsetting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dataroom_document__isnull', False), ('dataroom_folder__isnull', True)), models.Q(('dataroom_document__isnull', True), ('dataroom_folder__isnull', False)), _connector='OR'), name='sharelinkdataroomsetting_exactly_one_target'),
        ),
        migrations.AlterUniqueTogether(
            name='viewer',
            unique_together={('organization', 'email')},
        ),
    ]
