# Generated by Django 5.2.6 on 2026-05-30 04:43

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginactivity'),
        ('datarooms', '0003_dataroom_brand_accent_color_and_more'),
        ('documents', '0002_document_metadata'),
        ('sharelinks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QnAThread',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_threads_created', to=settings.AUTH_USER_MODEL)),
                ('created_by_view_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_threads_created', to='sharelinks.viewsession')),
                ('created_by_viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_threads_created', to='sharelinks.viewer')),
                ('dataroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_threads', to='datarooms.dataroom')),
                ('dataroom_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_threads', to='datarooms.dataroomdocument')),
                ('dataroom_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_threads', to='datarooms.dataroomfolder')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_threads', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_threads', to='core.organization')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_threads', to='sharelinks.sharelink')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QnAMessage',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('sent_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('sent_by_view_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_messages_sent', to='sharelinks.viewsession')),
                ('sent_by_viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_messages_sent', to='sharelinks.viewer')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sharelinks.qnathread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='qnathread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('dataroom__isnull', True), ('dataroom_document__isnull', True), ('dataroom_folder__isnull', True)), models.Q(('document__isnull', True), ('dataroom__isnull', False), ('dataroom_document__isnull', True), ('dataroom_folder__isnull', True)), models.Q(('document__isnull', True), ('dataroom__isnull', False), ('dataroom_document__isnull', False), ('dataroom_folder__isnull', True)), models.Q(('document__isnull', True), ('dataroom__isnull', False), ('dataroom_document__isnull', True), ('dataroom_folder__isnull', False)), _connector='OR'), name='qna_thread_exactly_one_context'),
        ),
        migrations.AddConstraint(
            model_name='qnathread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_by_user__isnull', False), ('created_by_view_session__isnull', True)), models.Q(('created_by_user__isnull', True), ('created_by_view_session__isnull', False)), _connector='OR'), name='qna_thread_exactly_one_creator_type'),
        ),
        migrations.AddConstraint(
            model_name='qnamessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sent_by_user__isnull', False), ('sent_by_view_session__isnull', True)), models.Q(('sent_by_user__isnull', True), ('sent_by_view_session__isnull', False)), _connector='OR'), name='qna_message_exactly_one_sender_type'),
        ),
    ]
