# Generated by Django 5.2.6 on 2025-11-20 05:47

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_avatar'),
        ('sharelinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLinkTemplate',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('expires_in_days', models.IntegerField(blank=True, null=True)),
                ('requires_password', models.BooleanField(default=False)),
                ('requires_email', models.BooleanField(default=False)),
                ('requires_email_verification', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=True)),
                ('enable_watermark', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, max_length=255)),
                ('receive_email_notification', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_link_templates', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ShareLinkPreset',
        ),
    ]
