# Generated by Django 5.2.6 on 2026-07-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0002_qnathread_qnamessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='is_fullscreen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='media_type',
            field=models.CharField(default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='pageview',
            name='playback_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='video_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='video_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='video_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
