# Generated by Django 5.2.6 on 2025-11-30 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0002_sharelinktemplate_delete_sharelinkpreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='share_links_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
