# Generated by Django 5.2.6 on 2026-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0003_pageview_is_fullscreen_pageview_is_muted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='media_type',
            field=models.CharField(default='document', max_length=20),
        ),
    ]
