# Generated by Django 5.2.6 on 2025-12-03 04:07

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0001_initial'),
        ('sharelinks', '0003_alter_sharelink_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataroomVisit',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataroom_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datarooms.dataroomdocument')),
                ('dataroom_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datarooms.dataroomfolder')),
                ('view_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataroom_visits', to='sharelinks.viewsession')),
            ],
            options={
                'ordering': ['visited_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dataroom_document__isnull', False), ('dataroom_folder__isnull', True)), models.Q(('dataroom_document__isnull', True), ('dataroom_folder__isnull', False)), _connector='OR'), name='dataroomvisit_exactly_one_target')],
            },
        ),
    ]
