# Generated by Django 5.2.6 on 2026-07-15 04:04

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0003_pageview_is_fullscreen_pageview_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('url', models.TextField()),
                ('page_number', models.PositiveIntegerField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('dataroom_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='sharelinks.dataroomvisit')),
                ('view_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='sharelinks.viewsession')),
            ],
            options={
                'ordering': ['clicked_at'],
            },
        ),
    ]
