# Generated by Django 5.2.6 on 2025-12-03 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0001_initial'),
        ('sharelinks', '0004_dataroomvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomvisit',
            name='dataroom_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarooms.dataroomdocument'),
        ),
        migrations.AlterField(
            model_name='dataroomvisit',
            name='dataroom_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarooms.dataroomfolder'),
        ),
    ]
