# Generated by Django 5.2.6 on 2026-07-15 07:40

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0004_linkclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='nda_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='nda_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='require_nda',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NDAAcceptance',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('nda_version', models.IntegerField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nda_acceptances', to='sharelinks.sharelink')),
                ('view_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nda_acceptances', to='sharelinks.viewsession')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nda_acceptances', to='sharelinks.viewer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('view_session__isnull', False), ('viewer__isnull', True)), models.Q(('view_session__isnull', True), ('viewer__isnull', False)), _connector='OR'), name='ndaacceptance_session_or_viewer')],
            },
        ),
    ]
