# Generated by Django 5.2.6 on 2026-07-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0004_pageview_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='is_muted',
        ),
        migrations.AddField(
            model_name='pageview',
            name='video_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
