# Generated by Django 5.2.6 on 2025-12-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0005_alter_dataroomvisit_dataroom_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='dataroom_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='sharelinks.dataroomvisit'),
        ),
    ]
