# Generated by Django 5.2.6 on 2026-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0005_sharelink_nda_text_sharelink_nda_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomvisit',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
