# Generated by Django 5.2.6 on 2025-12-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarooms', '0003_alter_dataroomdocument_name'),
        ('sharelinks', '0006_pageview_dataroom_visit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dataroomvisit',
            name='dataroomvisit_exactly_one_target',
        ),
        migrations.AddConstraint(
            model_name='dataroomvisit',
            constraint=models.CheckConstraint(condition=models.Q(('dataroom_document__isnull', False), ('dataroom_folder__isnull', False), _negated=True), name='dataroomvisit_not_both_targets'),
        ),
    ]
