# Generated by Django 5.2.6 on 2026-09-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0007_sharelink_enable_qna'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='viewsession',
            index=models.Index(fields=['share_link', '-viewed_at'], name='viewsession_link_viewed_idx'),
        ),
    ]
