# Generated by Django 5.2.6 on 2026-09-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0008_viewsession_viewsession_link_viewed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomvisit',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dataroomvisit',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dataroomvisit',
            name='item_path',
            field=models.CharField(blank=True, default='', help_text='Virtual folder path at time of visit, e.g. /Financials/2026', max_length=1024),
        ),
        migrations.AddField(
            model_name='dataroomvisit',
            name='item_type',
            field=models.CharField(blank=True, choices=[('document', 'Document'), ('folder', 'Folder')], default='document', max_length=20),
        ),
    ]
