# Generated by Django for DataroomVisit audit snapshot backfill

from django.db import migrations


def backfill_dataroom_visit_snapshots(apps, schema_editor):
    DataroomVisit = apps.get_model('sharelinks', 'DataroomVisit')
    DataroomDocument = apps.get_model('datarooms', 'DataroomDocument')
    DataroomFolder = apps.get_model('datarooms', 'DataroomFolder')
    Document = apps.get_model('documents', 'Document')

    folders_by_id = {
        folder.id: (folder.name, folder.parent_id)
        for folder in DataroomFolder.objects.all()
    }

    def get_path(folder_id):
        if not folder_id or folder_id not in folders_by_id:
            return '/'
        parts = []
        curr_id = folder_id
        visited = set()
        while curr_id and curr_id in folders_by_id and curr_id not in visited:
            visited.add(curr_id)
            name, parent_id = folders_by_id[curr_id]
            parts.append(name)
            curr_id = parent_id
        if not parts:
            return '/'
        return '/' + '/'.join(reversed(parts))

    doc_lookup = {
        doc.id: (doc.name, doc.type)
        for doc in Document.objects.all()
    }
    ddoc_lookup = {
        ddoc.id: (ddoc.name, ddoc.document_id, ddoc.folder_id)
        for ddoc in DataroomDocument.objects.all()
    }

    visits_to_update = []
    for visit in DataroomVisit.objects.filter(item_name='').iterator(chunk_size=1000):
        if visit.dataroom_document_id:
            ddoc_info = ddoc_lookup.get(visit.dataroom_document_id)
            if ddoc_info:
                ddoc_alias, doc_id, folder_id = ddoc_info
                doc_name, doc_type = doc_lookup.get(doc_id, ('', ''))
                visit.item_type = 'document'
                visit.item_name = ddoc_alias or doc_name
                visit.item_path = get_path(folder_id)
                visit.document_type = doc_type
                visits_to_update.append(visit)
        elif visit.dataroom_folder_id:
            folder_info = folders_by_id.get(visit.dataroom_folder_id)
            if folder_info:
                folder_name, _ = folder_info
                visit.item_type = 'folder'
                visit.item_name = folder_name
                visit.item_path = get_path(visit.dataroom_folder_id)
                visit.document_type = ''
                visits_to_update.append(visit)

        if len(visits_to_update) >= 1000:
            DataroomVisit.objects.bulk_update(
                visits_to_update,
                ['item_type', 'item_name', 'item_path', 'document_type']
            )
            visits_to_update = []

    if visits_to_update:
        DataroomVisit.objects.bulk_update(
            visits_to_update,
            ['item_type', 'item_name', 'item_path', 'document_type']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0009_dataroomvisit_document_type_dataroomvisit_item_name_and_more'),
        ('datarooms', '0005_dataroom_storage_quota_mb_dataroom_storage_version_and_more'),
        ('documents', '0007_alter_document_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_dataroom_visit_snapshots,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
