# Generated by Django 5.2.6 on 2026-10-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharelinks', '0010_backfill_dataroom_visit_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='scroll_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
