# Generated by Django 5.2.6 on 2026-02-14 03:07

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_upload_info'),
        ('filerequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader_name', models.CharField(max_length=255)),
                ('uploader_email', models.EmailField(max_length=254)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_via_file_request', to='documents.document')),
                ('file_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='filerequests.filerequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
