# Generated by Django 5.2.6 on 2026-05-25 14:13

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginactivity'),
        ('filerequests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityThreatEvent',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('malware_detected', 'Malware Detected'), ('scan_failed', 'Scanner Failed')], max_length=32)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium')], max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=1024)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('uploader_name', models.CharField(blank=True, max_length=255)),
                ('uploader_email', models.EmailField(blank=True, max_length=254)),
                ('scanner_engine', models.CharField(default='clamav', max_length=64)),
                ('scanner_message', models.TextField(blank=True)),
                ('storage_cleanup_status', models.CharField(choices=[('pending', 'Pending'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('storage_cleanup_at', models.DateTimeField(blank=True, null=True)),
                ('storage_cleanup_error', models.TextField(blank=True)),
                ('file_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_threat_events', to='filerequests.filerequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_threat_events', to='core.organization')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_threat_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
