# Generated by Django 5.2.6 on 2026-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filerequests', '0002_securitythreatevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, help_text='Optional public intake field schema for this file request.'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='submitted_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
