# Generated by Django 5.2.6 on 2026-02-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filerequests', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='filerequest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
