# Generated by Django 5.2.6 on 2026-07-12 02:44

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudfiles', '0001_initial'),
        ('filerequests', '0003_filerequest_custom_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadExportJob',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_folder_id', models.CharField(help_text='Folder ID or destination path.', max_length=1024)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('exporting', 'Exporting'), ('exported', 'Exported'), ('failed', 'Failed'), ('blocked_security_scan', 'Blocked (Security Scan)'), ('blocked_policy', 'Blocked (Policy)')], default='queued', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_file_id', models.CharField(blank=True, default='', help_text='File ID in remote storage.', max_length=1024)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='cloudfiles.cloudconnection')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='filerequests.uploadedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
