# Generated by Django 5.2.6 on 2025-12-12 05:58

import core.fields
import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudConnection',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[core.fields.validate_ulid])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('dropbox', 'Dropbox'), ('google_drive', 'Google Drive'), ('nextcloud', 'Nextcloud')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('access_token', django_cryptography.fields.encrypt(models.TextField())),
                ('refresh_token', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
