# Generated by Django 5.2.6 on 2025-11-30 10:36

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudconnection',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='cloudconnection',
            name='provider',
            field=models.CharField(choices=[('dropbox', 'Dropbox'), ('google_drive', 'Google Drive'), ('nextcloud', 'Nextcloud')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudconnection',
            name='refresh_token',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
    ]
