# Generated by Django 5.2.6 on 2026-07-04 04:53

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_logo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.organization_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AddField(
            model_name='organization',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='brand_website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='branding_extras',
            field=models.JSONField(blank=True, default=dict, validators=[core.models.validate_branding_extras]),
        ),
    ]
