# Generated by Django 5.2.6 on 2026-07-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_brand_logo_organization_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_file_size_quota_mb',
            field=models.IntegerField(blank=True, help_text='Per-user custom file size quota in MB. If null, the global config is used. 0 means unlimited.', null=True),
        ),
    ]
