# Generated by Django 5.2.6 on 2025-11-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_document_size',
            field=models.BigIntegerField(default=0, help_text='Total size of all documents in bytes.'),
        ),
    ]
