# Generated by Django 5.2.6 on 2026-08-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('ru', 'Russian')], default='en', help_text='Preferred UI language', max_length=10),
        ),
    ]
