# Generated by Django 5.2.6 on 2025-11-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_total_document_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, help_text='A description of what this setting controls.')),
            ],
            options={
                'verbose_name': 'Application Configuration',
                'verbose_name_plural': 'Application Configurations',
                'ordering': ('key',),
            },
        ),
    ]
