# Generated by Django 5.2.6 on 2026-08-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh-hans', 'Simplified Chinese'), ('ru', 'Russian'), ('de', 'German')], default='en', help_text='Preferred UI language', max_length=10),
        ),
    ]
